### PR TITLE
Added latest versions of the providers

### PR DESCRIPTION
**Pull request by bladeoner**
Hi @wardviaene,

I have added the latest providers and added a gitignore exclusion for the .terraform.lock.hcl files.

### CODE REVIEW

**Comment by bladeoner** [comment]
Hi @wardviaene I also opened this PR, if you have time can you take a look?

Thanks in advance.

**Comment by wardviaene** [comment]
Hi,

Any reason you want to exclude the lock files? Terraform documentation also recommends to commit the lock files (see https://developer.hashicorp.com/terraform/language/files/dependency-lock):

```
Terraform automatically creates or updates the dependency lock file each time you run [the terraform init command](https://developer.hashicorp.com/terraform/cli/commands/init). You should include this file in your version control repository so that you can discuss potential changes to your external dependencies via code review, just as you would discuss potential changes to your configuration itself.
```

It makes sure that the demos still work, even if there's a new version available. You can then upgrade the version if new features are needed that are not in the current version.

**Comment by bladeoner** [comment]
Hi @wardviaene thank you for sharing the information. I thought because there are lock files they should be handled like the other lock files and not included in the repository. I didn't know that these specific files should be included in the repository.

I have just rebased my commit to only include the latest versions of the providers.

**Comment by wardviaene** [comment]
Thank you!

**Comment by bladeoner** [comment]
You are welcome

**Pull request merged**
